;(function(global){
	global.Ta=global.Ta||{};
	Ta.hack=function(){
		return {params:'',
			conf:{sid:9945000,pf:2,hot:{}}		};
	};
})(this);

(function(f,r){function u(d){return(d=document.cookie.match(RegExp("(?:^|;\\s)"+d+"=(.*?)(?:;\\s|$)")))?d[1]:""}function v(d,a,b){var d=d+"="+a+";path=/;domain=",a=window.location.host,c={"com.cn":1,"net.cn":1,"gov.cn":1,"com.hk":1},e=a.split(".");2<e.length&&(a=(c[e.slice(-2).join(".")]?e.slice(-3):e.slice(-2)).join("."));document.cookie=d+a+(b?";expires="+b:"")}function s(d){var a,b,c,e={};void 0===d?(c=window.location,d=c.host,a=c.pathname,b=c.search.substr(1),c=c.hash):(c=d.match(/\w+:\/\/((?:[\w-]+\.)+\w+)(?:\:\d+)?(\/[^\?\\\"\'\|\:<>]*)?(?:\?([^\'\"\\<>#]*))?(?:#(\w+))?/i)||
[],d=c[1],a=c[2],b=c[3],c=c[4]);if(b)for(var f=b.split("&"),l=0,q=f.length;l<q;l++){var m=f[l].split("=");e[m[0]]=m[1]}return{host:d,path:a,search:b,hash:c,param:e}}function w(d){return(d||"")+Math.round(2147483647*(Math.random()||0.5))*+new Date%1E10}function x(d,a){var b=document.createElement("script"),c=document.getElementsByTagName("script")[0];b.src=d;b.type="text/javascript";b.onload=b.onerror=b.onreadystatechange=function(){/loaded|complete|undefined/.test(b.readyState)&&(b.onload=b.onerror=
b.onreadystatechange=null,b.parentNode.removeChild(b),b=void 0,a())};c.parentNode.insertBefore(b,c)}function t(d){d=d||{};if(d.conf){var a=d.conf,b;for(b in a)a.hasOwnProperty(b)&&(f[b]=a[b])}if(f.sid&&!Ta[f.sid]){a=[];b=0;var c=s(),c={dm:c.host,pvi:"",si:"",url:c.path,arg:encodeURIComponent(c.search||""),ty:1},e=u("pgv_pvi");e||(c.ty=0,e=w(),v("pgv_pvi",e,"Sun, 18 Jan 2038 00:00:00 GMT;"));c.pvi=e;e=u("pgv_si");e||(e=w("s"),v("pgv_si",e));c.si=e;var e=s(document.referrer),p=s(),e={rdm:e.host,rurl:e.path,
rarg:encodeURIComponent(e.search||""),adt:p.param.ADTAG||p.param.adtag},p={r2:f.sid,r3:"undefined"==typeof _speedMark?"-1":new Date-_speedMark,r4:f.pf||1},l;a:{try{var q=navigator,m=screen||{width:"",height:"",colorDepth:""},n=document.body,r=m.width+"x"+m.height,t=m.colorDepth+"-bit",A=(q.language||q.userLanguage).toLowerCase(),B=q.javaEnabled()?1:0,C=(new Date).getTimezoneOffset()/60,m="";n.addBehavior&&(n.addBehavior("#default#clientCaps"),m=n.connectionType);var n={fl:"",scr:r,scl:t,lg:A,jv:B,
tz:C,ct:m},k,g,h;if((l=q.plugins)&&(k=l.length))for(h=0;h<k;h++){if(g=l[h].description.match(/Shockwave Flash ([\d\.]+) \w*/))n.fl=g[1]}else h=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"),n.fl=h.replace(/^.*\s+(\d+)\,(\d+).*$/,"$1.$2")}catch(E){l={};break a}l=n}var j;k={};if("undefined"!=typeof _taadHolders&&0<_taadHolders.length){g=0;h=_taadHolders;for(n=h.length;g<n;g++)k[h[g]]=k[h[g]]?k[h[g]]+1:1}g=[];for(j in k)k.hasOwnProperty(j)&&g.push(j+"*"+k[j]);j={ext:"adid="+
g.join(":")};g=u("pgv_ssid");k="";(h=(h=/ssid=([^&]*)/i.exec(s().hash))&&h[1]?h[1]:"")?(k="ty=0;ck=0;id="+h,g=new Date,g.setTime(g.getTime()+2592E6),v("pgv_ssid",h,g.toGMTString())):g&&(k="ty=0;ck=1;id="+g);c=[c,e,p,l,j,{pf:k},{random:+new Date}];for(j=c.length;b<j;b++)for(var i in c[b])c[b].hasOwnProperty(i)&&a.push(i+"="+(c[b][i]||""));d.params&&a.push(d.params);var y=Ta.src=("https:"==document.location.protocol?"https://pingtas":"http://pingtcss")+".qq.com/pingd?"+a.join("&"),o=new Image;Ta[f.sid]=
o;o.onload=o.onerror=o.onabort=function(){o=o.onload=o.onerror=o.onabort=null;Ta[f.sid]=true};o.src=y;if(1*!f.pf||f.hot.isValid){d=window.location;i=d.host+d.pathname;var D=d.pathname,z=function(){x("http://imgcache.qq.com/bossweb/ta/scripts/ping_hotclick_min.js",function(){window.hotclick&&(new hotclick(y)).watchClick()})};if(1*f.pf&&RegExp(i).test(f.hot.url))z();else{i=f.sid;d="http://tcss.qq.com/heatmap/"+i%100+"/";i+="";c=i.length;b=0;for(a="";b<c;){j=i.charCodeAt(b++)&255;if(b==c){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(j>>
2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((j&3)<<4);a+="==";break}e=i.charCodeAt(b++);if(b==c){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(j>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((j&3)<<4|(e&240)>>4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&15)<<2);a+="=";break}p=i.charCodeAt(b++);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(j>>
2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((j&3)<<4|(e&240)>>4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&15)<<2|(p&192)>>6);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(p&63)}x(d+a+".js?random="+ +new Date,function(){var a;if(window._Cnf&&(a=window._Cnf.url)){a=a.split("|");for(var b=0;b<a.length;b++)if(a[b]==D){z();break}}})}}f.logo&&255!=f.logo&&(d=f.logo,i={9:"\u817e\u8baf\u5206\u6790",10:"\u7f51\u7ad9\u7edf\u8ba1",
df:'<img src="http://tcss.qq.com/icon/toss_'+d+'.gif" border="0" />'},document.write(['<a href="http://ta.qq.com?ADTAG=FROUM.FOOTER.CLICK.ICON" title="\u817e\u8baf\u5206\u6790" target="_blank">',i[d]||i.df,"<a>"].join("")))}}r.pgvSendClick=function(d,a){var b=Ta.src.replace(/ext=[^&]*/,function(){return"ext="+("evtid"==a?"ty=0;evtid=":"adid=")+d}).replace(/r2=([^&]*)/,function(a,b){return"r2=a"+b});(new Image(1,1)).src=b};r.Ta=r.Ta||{};Ta.pgv=t;!Ta.async&&t(Ta.hack?Ta.hack():"")})({sid:"",pf:"",hot:{url:"",
isValid:!1}},this);
