;(function(global){
	global.Ta=global.Ta||{};
	Ta.hack=function(){
		return {params:'',
			conf:{sid:11270228,pf:2,hot:{}}		};
	};
})(this);
(function(f,j){function q(b){var b=b+"",a,c,d,e,h,g;d=b.length;c=0;for(a="";c<d;){e=b.charCodeAt(c++)&255;if(c==d){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&3)<<4);a+="==";break}h=b.charCodeAt(c++);if(c==d){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&3)<<4|(h&240)>>
4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((h&15)<<2);a+="=";break}g=b.charCodeAt(c++);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&3)<<4|(h&240)>>4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((h&15)<<2|(g&192)>>6);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g&63)}return a}function k(b){return(b=
document.cookie.match(RegExp("(?:^|;\\s)"+b+"=(.*?)(?:;\\s|$)")))?b[1]:""}function m(b,a,c){var b=b+"="+a+";path=/;domain=",a=window.location.host,d={"com.cn":1,"net.cn":1,"gov.cn":1,"com.hk":1},e=a.split(".");2<e.length&&(a=(d[e.slice(-2).join(".")]?e.slice(-3):e.slice(-2)).join("."));document.cookie=b+a+(c?";expires="+c:"")}function i(b){var a,c,d,e={};void 0===b?(d=window.location,b=d.host,a=d.pathname,c=d.search.substr(1),d=d.hash):(d=b.match(/\w+:\/\/((?:[\w-]+\.)+\w+)(?:\:\d+)?(\/[^\?\\\"\'\|\:<>]*)?(?:\?([^\'\"\\<>#]*))?(?:#(\w+))?/i)||
[],b=d[1],a=d[2],c=d[3],d=d[4]);if(c)for(var h=c.split("&"),g=0,f=h.length;g<f;g++){var l=h[g].split("=");e[l[0]]=l[1]}return{host:b,path:a,search:c,hash:d,param:e}}function n(b){return(b||"")+Math.round(2147483647*(Math.random()||0.5))*+new Date%1E10}function o(b,a){var c=document.createElement("script"),d=document.getElementsByTagName("script")[0];c.src=b;c.type="text/javascript";c.onload=c.onerror=c.onreadystatechange=function(){/loaded|complete|undefined/.test(c.readyState)&&(c.onload=c.onerror=
c.onreadystatechange=null,c.parentNode.removeChild(d),c=void 0,a())};d.parentNode.insertBefore(c,d)}function r(){var b=i(),a={dm:b.host,pvi:"",si:"",url:b.path,arg:encodeURIComponent(b.search||""),ty:1};a.pvi=function(){var b=k("pgv_pvi");b||(a.ty=0,b=n(),m("pgv_pvi",b,"Sun, 18 Jan 2038 00:00:00 GMT;"));return b}();a.si=function(){var a=k("pgv_si");a||(a=n("s"),m("pgv_si",a));return a}();return a}function s(){var b=i(document.referrer),a=i();return{rdm:b.host,rurl:b.path,rarg:encodeURIComponent(b.search||
""),adt:a.param.ADTAG||a.param.adtag}}function t(){try{var b=navigator,a=screen||{width:"",height:"",colorDepth:""},c=document.body,d=a.width+"x"+a.height,e=a.colorDepth+"-bit",h=(b.language||b.userLanguage).toLowerCase(),g=b.javaEnabled()?1:0,f=(new Date).getTimezoneOffset()/60,a="";c.addBehavior&&(c.addBehavior("#default#clientCaps"),a=c.connectionType);var c={fl:"",scr:d,scl:e,lg:h,jv:g,tz:f,ct:a},l,i,j,k;if((l=b.plugins)&&(i=l.length))for(b=0;b<i;b++){if(j=l[b].description.match(/Shockwave Flash ([\d\.]+) \w*/))c.fl=
j[1]}else k=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"),c.fl=k.replace(/^.*\s+(\d+)\,(\d+).*$/,"$1.$2")}catch(m){return{}}return c}function u(){var b={};if("undefined"!=typeof _taadHolders&&0<_taadHolders.length)for(var a=0,c=_taadHolders,d=c.length;a<d;a++)b[c[a]]=b[c[a]]?b[c[a]]+1:1;var a=[],e;for(e in b)b.hasOwnProperty(e)&&a.push(e+"*"+b[e]);return{ext:"adid="+a.join(":")}}function v(){var b=k("pgv_ssid"),a="",c;(c=(c=/ssid=([^&]*)/i.exec(i().hash))&&c[1]?c[1]:
"")?(a="ty=0;ck=0;id="+c,b=new Date,b.setTime(b.getTime()+2592E6),m("pgv_ssid",c,b.toGMTString())):b&&(a="ty=0;ck=1;id="+b);return{pf:a}}function p(b){b=b||{};b.conf&&function(){var a=b.conf,c;for(c in a)a.hasOwnProperty(c)&&(f[c]=a[c])}();if(f.sid&&!Ta[f.sid]){for(var a=[],c=0,d=[r(),s(),{r2:f.sid,r3:"undefined"==typeof _speedMark?"-1":new Date-_speedMark,r4:f.pf||1},t(),u(),v(),{random:+new Date}],e=d.length;c<e;c++)for(var h in d[c])d[c].hasOwnProperty(h)&&a.push(h+"="+(d[c][h]||""));b.params&&
a.push(b.params);var a=Ta.src=("https:"==document.location.protocol?"https://pingtas":"http://pingtcss")+".qq.com/pingd?"+a.join("&"),g=new Image;Ta[f.sid]=g;g.onload=g.onerror=g.onabort=function(){g=g.onload=g.onerror=g.onabort=null;Ta[f.sid]=!0};g.src=a;(1*!f.pf||f.hot.isValid)&&w(a);f.logo&&255!=f.logo&&x(f.logo)}}function w(b){var a=window.location,c=a.host+a.pathname,d=a.pathname,e=function(){o("http://imgcache.qq.com/bossweb/ta/scripts/ping_hotclick_min.js",function(){window.hotclick&&(new hotclick(b)).watchClick()})};
1*f.pf&&RegExp(c).test(f.hot.url)?e():(a=f.sid,o("http://tcss.qq.com/heatmap/"+a%100+"/"+q(a)+".js?random="+ +new Date,function(){var a;if(window._Cnf&&(a=window._Cnf.url)){a=a.split("|");for(var b=0;b<a.length;b++)if(a[b]==d){e();break}}}))}function x(b){var a={9:"\u817e\u8baf\u5206\u6790",10:"\u7f51\u7ad9\u7edf\u8ba1",df:'<img src="http://tcss.qq.com/icon/toss_'+b+'.gif" border="0" />'};document.write(['<a href="http://ta.qq.com?ADTAG=FROUM.FOOTER.CLICK.ICON" title="\u817e\u8baf\u5206\u6790" target="_blank">',
a[b]||a.df,"<a>"].join(""))}j.pgvSendClick=function(b,a){var c=Ta.src.replace(/ext=[^&]*/,function(){return"ext="+("evtid"==a?"ty=0;evtid=":"adid=")+b}).replace(/r2=([^&]*)/,function(a,b){return"r2=a"+b});(new Image(1,1)).src=c};j.Ta=j.Ta||{};Ta.pgv=p;!Ta.async&&p(Ta.hack?Ta.hack():"")})({sid:"",pf:"",hot:{url:"",isValid:!1}},this);
